apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\rizka\Downloads\project\go\deall-job-interview\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
